### ISSUE TITLE
Giving an error when trying to install on supervisor version 2024.11.4

### ISSUE THREAD

**Issue by chickey** [benoit505/ha-inventree#3]
The version 0f3ddae for this integration can not be used with HACS.

**Comment by benoit505** [comment]
hi, first project on HACS here, I've created and pushed a GitHub Actions workflow, created a proper v1.1.0 release. 
You should now be able to 
1. Add a custom repository with https://github.com/benoit505/ha-inventree as URL
2. Select type: Integration

The issue should be resolved.
Want to let me know how it goes?

**Comment by chickey** [comment]
Working now thanks.
